---
deployment:
tasks:
  - export DEPLOYPATH=/home/id16354291/public_html/
  - /bn/cp index.html $DEPLOYPATH
  - /bin/cp style.css $DEPLOYPATH
  - /bin/cp jumble.js $DEPLOYPATH
  - /bin/cp -R img $DEPLOYPATH
